/*
 * DIO_config.h
 *
 *  Created on: May 22, 2020
 *      Author: KAPOO
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/* Config for The initial directions */
/* Options : DIO_u8_INPUT
		     DIO_u8_OUTPUT */
#define DIO_u8_PIN0_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN1_PORTA_INITIAL_DIRC			   DIO_u8_INPUT
#define DIO_u8_PIN2_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN3_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN4_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN5_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN6_PORTA_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN7_PORTA_INITIAL_DIRC             DIO_u8_INPUT


#define DIO_u8_PIN0_PORTB_INITIAL_DIRC             DIO_u8_OUTPUT
#define DIO_u8_PIN1_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN2_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN3_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN4_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN5_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN6_PORTB_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN7_PORTB_INITIAL_DIRC             DIO_u8_INPUT


#define DIO_u8_PIN0_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN1_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN2_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN3_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN4_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN5_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN6_PORTC_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN7_PORTC_INITIAL_DIRC             DIO_u8_INPUT


#define DIO_u8_PIN0_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN1_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN2_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN3_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN4_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN5_PORTD_INITIAL_DIRC             DIO_u8_OUTPUT
#define DIO_u8_PIN6_PORTD_INITIAL_DIRC             DIO_u8_INPUT
#define DIO_u8_PIN7_PORTD_INITIAL_DIRC             DIO_u8_INPUT

/* Macros for the Initial values of the pins */
/* Options :DIO_u8_INITIAL_HIGH
            DIO_u8_INITIAL_LOW
            DIO_u8_INITIAL_PULLUP */
#define DIO_u8_PIN0_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_PULLUP
#define DIO_u8_PIN1_PORTA_INITIAL_VALUE			   DIO_u8_INITIAL_LOW
#define DIO_u8_PIN2_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN3_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN4_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN5_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN6_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN7_PORTA_INITIAL_VALUE            DIO_u8_INITIAL_LOW


#define DIO_u8_PIN0_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN1_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN2_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN3_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN4_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN5_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN6_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN7_PORTB_INITIAL_VALUE            DIO_u8_INITIAL_LOW


#define DIO_u8_PIN0_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN1_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN2_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN3_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN4_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN5_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN6_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN7_PORTC_INITIAL_VALUE            DIO_u8_INITIAL_LOW


#define DIO_u8_PIN0_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN1_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN2_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN3_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN4_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN5_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN6_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW
#define DIO_u8_PIN7_PORTD_INITIAL_VALUE            DIO_u8_INITIAL_LOW


#endif /* DIO_CONFIG_H_ */
